name: "Common JS Steps"
description: "Checkout code, setup Node and install dependencies using yarn"

branding:
  icon: activity
  color: gray-dark
  
inputs:
  token:
    description: 'Specify token for access to resources.'
    required: true

runs:
  using: "composite"
  steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ inputs.token }}

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          token: ${{ inputs.token }}
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
